import {
  IconArrowLeft,
  IconArrowRight,
  IconLogin,
  IconLogout,
  IconMoon,
  IconSunny,
  IconPlay,
  IconPause,
  IconFolderEmpty,
  IconIcon,
  IconColor,
  IconFont,
  IconBP,
  IconDesign,
  IconComponents,
  IconPart,
  IconModule,
  IconLayout,
  IconHook,
  IconCode,
  IconCubeTransparent,
  IconClose,
  IconList,
  IconEllipsis,
  IconOutLink,
  IconSearch,
  IconBack,
  IconCheck,
  IconFolderAdd,
  IconAirport,
  IconChat,
  IconCalendar,
  IconMoney,
  IconPen,
  IconRunning,
  IconLock,
  IconUnlock,
  IconUser,
  IconTogether,
  IconBookmark,
  IconUnBookmark,
  IconKey,
  IconGoogle,
  IconTrash,
  IconEmail,
  IconAccess,
  IconWarning,
  IconRank,
  IconTheme,
  IconEyeClosed,
  IconEye,
  IconSign,
  IconOpenView,
  IconRotate,
} from "@/assets/icon";

//🔹 iconData.ts 동일하게

export const IconMatchLists = {
  'icon-search': IconSearch,
  'icon-moon': IconMoon,
  'icon-sunny': IconSunny,
  'icon-login': IconLogin,
  'icon-logout':IconLogout,
  'icon-arrow-left': IconArrowLeft,
  'icon-arrow-right': IconArrowRight,
  'icon-play': IconPlay,
  'icon-pause': IconPause,
  'icon-folder-empty': IconFolderEmpty,
  'icon-icon': IconIcon,
  'icon-color': IconColor,
  'icon-font': IconFont,
  'icon-break-point': IconBP,
  'icon-design': IconDesign,
  'icon-components': IconComponents,
  'icon-part': IconPart,
  'icon-multiple': IconModule,
  'icon-layout': IconLayout,
  'icon-hook': IconHook,
  'icon-code': IconCode,
  'icon-cube-transparent': IconCubeTransparent,
  'icon-close': IconClose,
  'icon-list': IconList,
  'icon-ellipsis': IconEllipsis,
  'icon-out-link': IconOutLink,
  'icon-back' : IconBack,
  'icon-check' : IconCheck,
  'icon-folder-add' : IconFolderAdd,
  'icon-airport': IconAirport,
  'icon-chat': IconChat,
  'icon-calendar': IconCalendar,
  'icon-money': IconMoney,
  'icon-pen': IconPen,
  'icon-running': IconRunning,
  'icon-lock': IconLock,
  'icon-unlock': IconUnlock,
  'icon-user': IconUser,
  'icon-together': IconTogether,
  'icon-bookmark': IconBookmark,
  'icon-unbookmark': IconUnBookmark,
  'icon-key': IconKey,
  'icon-trash': IconTrash,
  'icon-google': IconGoogle,
  'icon-email': IconEmail,
  'icon-rank': IconRank,
  'icon-theme':IconTheme,
  'icon-sign':IconSign,
  'icon-access': IconAccess,
  'icon-warning': IconWarning,
  'icon-eye': IconEye,
  'icon-eye-closed': IconEyeClosed,
  'icon-open-view' : IconOpenView,
  'icon-rotate': IconRotate,
} as const;
