import {
  IconArrowLeft,
  IconArrowRight,
  IconLogin,
  IconMoon,
  IconSunny,
  IconPlay,
  IconPause,
  IconFolderEmpty,
  IconIcon,
  IconColor,
  IconFont,
  IconBP,
  IconDesign,
  IconComponents,
  IconPart,
  IconModule,
  IconLayout,
  IconHook,
  IconCode,
  IconCubeTransparent,
  IconClose,
  IconList,
  IconEllipsis,
  IconOutLink,
  IconSearch,
  IconBack,
  IconCheck,
  IconFolderAdd,
} from "@/assets/icon";

//🔹 iconData.ts 동일하게

export const IconMatchLists = {
  'icon-search': IconSearch,
  'icon-moon': IconMoon,
  'icon-sunny': IconSunny,
  'icon-login': IconLogin,
  'icon-arrow-left': IconArrowLeft,
  'icon-arrow-right': IconArrowRight,
  'icon-play': IconPlay,
  'icon-pause': IconPause,
  'icon-folder-empty': IconFolderEmpty,
  'icon-icon': IconIcon,
  'icon-color': IconColor,
  'icon-font': IconFont,
  'icon-break-point': IconBP,
  'icon-design': IconDesign,
  'icon-components': IconComponents,
  'icon-part': IconPart,
  'icon-multiple': IconModule,
  'icon-layout': IconLayout,
  'icon-hook': IconHook,
  'icon-code': IconCode,
  'icon-cube-transparent': IconCubeTransparent,
  'icon-close': IconClose,
  'icon-list': IconList,
  'icon-ellipsis': IconEllipsis,
  'icon-out-link': IconOutLink,
  'icon-back' : IconBack,
  'icon-check' : IconCheck,
  'icon-folder-add' : IconFolderAdd,
} as const;
